# Generated by Django 4.1.4 on 2022-12-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('AN', 'Anonimo'), ('NR', 'normal'), ('AD', 'admin')], default='AN', max_length=2),
        ),
    ]
