# Generated by Django 4.1.4 on 2022-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('AN', 'anonimo'), ('NR', 'normal'), ('AD', 'admin')], default='AN', max_length=2),
        ),
    ]
