# Generated by Django 4.1.4 on 2022-12-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_services_payment_user_expired_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expired_payments',
            old_name='Payment_usuario',
            new_name='payment_usuario',
        ),
        migrations.RenameField(
            model_name='expired_payments',
            old_name='Penalty_fee_amount',
            new_name='penalty_fee_amount',
        ),
        migrations.RenameField(
            model_name='payment_user',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment_user',
            old_name='Service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='payment_user',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
