# Generated by Django 4.1.4 on 2022-12-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_rename_payment_usuario_expired_payments_payment_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_user',
            old_name='ExpirationDate',
            new_name='expirationDate',
        ),
        migrations.RenameField(
            model_name='payment_user',
            old_name='PaymentDate',
            new_name='paymentDate',
        ),
    ]
