# Generated by Django 4.1.4 on 2022-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_rename_expirationdate_payment_user_expirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_user',
            name='expirationDate',
            field=models.DateField(),
        ),
    ]
